language: python
python:
  - "3.6"
cache: pip
install:
  - pip install .
  - pip install pytest-cov
  - pip install codecov
script:
  - python -m pytest --cov-report term --cov=pytwoway/
after_success:
  - codecov