name: pytw-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pybind11
  - ipython
  - jupyterlab
  - notebook
  - pytest
  - numpy
  - pandas
  - bipartitepandas
  - scipy
  - pyamg
  - qpsolvers
  - configargparse
  - matplotlib
  - tqdm
  - nbsphinx
  - pip:
      - sphinx-rtd-theme # Sphinx theme
      - pyarrow

# conda env create --file environment.yml
# conda env remove --name pytw-env
