name: twfe-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python   # or 2.7 if you are feeling nostalgic
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - pylint
  - pyamg
  - pyreadr
  - tqdm
  - networkx
  - scikit-learn
  - mkdocs-material
  - pip
  - pip:
      - mkdocstrings
      - mkdocs-material-extensions
      # - mknotebooks
      # - Pygments # Required for mknotebooks syntax highlighting
      - mkdocs-jupyter

# conda env create --file environment.yml
# conda env remove --name twfe-env
