# mkdocs.yml
site_name: PyTwoWay Documentation

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings
  # - mknotebooks
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.mark
  # - codehilite # For mknotebooks syntax highlighting

nav:
  - Home: index.md
  - twfe_network:
    - Documentation: twfe_network-reference.md
    - Example: PyTwoWay_Example.ipynb
  - sim_twfe_network:
    - Documentation: sim_twfe_network-reference.md
    - Example: Monte_Carlo_Example.ipynb
  - fe_approximate_correction_full: fe-reference.md
