# mkdocs.yml
site_name: PyTwoWay Documentation

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.mark

nav:
  - Home: index.md
  - twfe_network: twfe_network-reference.md
  - fe_approximate_correction_full: fe-reference.md
